# Generated by Django 3.1.6 on 2021-03-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0003_auto_20210313_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.grupo', verbose_name='Grupo')),
            ],
        ),
    ]
