# Generated by Django 3.1.6 on 2021-03-16 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0002_auto_20210314_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='maestro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Maestro'),
        ),
    ]
