# Generated by Django 3.1.6 on 2021-03-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0004_auto_20210316_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Maestro'),
        ),
    ]
