# Generated by Django 3.1.6 on 2021-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='tipo_evento',
            field=models.CharField(choices=[('success', 'Verde'), ('warning', 'Amarilla'), ('info', 'Aqua'), ('primary', 'Azul'), ('danger', 'Roja')], default='success', max_length=10, verbose_name='Tipo'),
        ),
    ]
