# Generated by Django 3.1.6 on 2021-03-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_eventocalendario_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
    ]
