# Generated by Django 3.1.6 on 2021-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_eventocalendario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='tipo_evento',
            field=models.CharField(max_length=6, verbose_name='Tipo'),
        ),
    ]
