# Generated by Django 3.1.6 on 2021-03-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_auto_20210323_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='tipo_evento',
            field=models.CharField(max_length=10, verbose_name='Tipo'),
        ),
    ]
