# Generated by Django 3.1.6 on 2021-03-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_auto_20210313_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='enrolado',
        ),
    ]
