# Generated by Django 3.1.6 on 2021-03-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_remove_grupo_enrolado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
