# Generated by Django 3.1.6 on 2021-03-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_auto_20210314_1529'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='user',
        ),
        migrations.AddField(
            model_name='tarea',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='materias.materia', verbose_name='Materia'),
        ),
    ]
