# Generated by Django 3.1.6 on 2021-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20210316_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='documento',
            field=models.FileField(default='null', upload_to='documentos/'),
        ),
    ]
