# Generated by Django 3.1.6 on 2021-03-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(choices=[('maestro', 'Maestro'), ('alumno', 'Alumno'), ('padre', 'Padre'), ('admin', 'Admin')], default='maestro', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.tipo'),
        ),
    ]
