# Generated by Django 3.1.6 on 2021-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210312_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipo',
        ),
        migrations.AddField(
            model_name='user',
            name='tipoUsuario',
            field=models.CharField(choices=[('maestro', 'Maestro'), ('alumno', 'Alumno'), ('padre', 'Padre'), ('admin', 'Admin')], default='maestro', max_length=10, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='null', upload_to='users/', verbose_name='Imagen del Usuario'),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
