# Generated by Django 3.1.6 on 2021-03-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210312_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
