# Generated by Django 3.1.6 on 2021-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210312_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipo',
        ),
        migrations.AddField(
            model_name='user',
            name='tipoUsuario',
            field=models.CharField(choices=[('maestro', 'Maestro'), ('alumno', 'Alumno'), ('padre', 'Padre'), ('admin', 'Admin')], default='maestro', max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
