# Generated by Django 3.1.6 on 2021-03-18 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210317_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=12, verbose_name='CURP')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('padre', models.CharField(max_length=100, verbose_name='Padre')),
                ('madre', models.CharField(max_length=100, verbose_name='Madre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('alumno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alummo')),
            ],
        ),
    ]
