# Generated by Django 3.1.6 on 2021-03-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_datosalumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosalumno',
            name='alumno',
        ),
        migrations.AddField(
            model_name='user',
            name='datosAlumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.datosalumno', verbose_name='Datos Alumno'),
        ),
    ]
