# Generated by Django 3.1.6 on 2021-03-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_auto_20210316_1308'),
        ('user', '0010_auto_20210318_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datosAlumno',
        ),
        migrations.AddField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='madre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Madre'),
        ),
        migrations.AddField(
            model_name='user',
            name='padecimientos',
            field=models.TextField(default='', verbose_name='Padecimientos'),
        ),
        migrations.AddField(
            model_name='user',
            name='padre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Padre'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.grupo', verbose_name='Grupo'),
        ),
        migrations.DeleteModel(
            name='DatosAlumno',
        ),
    ]
