# Generated by Django 3.1.6 on 2021-03-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0008_auto_20210316_1257'),
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque1', models.FloatField(verbose_name='Bloque 1')),
                ('bloque2', models.FloatField(verbose_name='Bloque 1')),
                ('bloque3', models.FloatField(verbose_name='Bloque 1')),
                ('semestral', models.FloatField(verbose_name='Semestral')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia', verbose_name='Materia')),
            ],
        ),
    ]
