# Generated by Django 3.1.6 on 2021-03-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_auto_20210325_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calificaciones.periodo', verbose_name='Periodo'),
        ),
    ]
